#!/bin/bash

self=.

main () {
    id=$(<@id)
    test -s @LOCK || tob $self.lock-route $id || exit
    trap "tob $self.unlock-route" EXIT TERM
    route=$(<@LOCK)
    base=${route%% *}
    repeaters=${route#* }
    echo $base > @base
    echo $repeaters > @route
    test "$repeaters" == $base &&{
        unset repeaters
        >@route
        }
    radio=$(<@radio)
    options=( --tag "$id" )
    TOB_get_attr \@prompt && options=( "${options[@]}" --prompt $attr )
    TOB_get_attr \@retries && options=( "${options[@]}" --retries $attr )
    t0=$(date +%s)
    echo tob $base.call "${options[@]}" $radio $repeaters
    tob $base.call "${options[@]}" $radio $repeaters
    t1=$(date +%s)
    test -s $base/\@session && {
        echo $t1 > @last-session-end-time
        cp $base/\@session \@session
        test -d sessions && tob sessions.store < \@session &
        }
    tob $self.unlock-route --no-log $id &&
        trap - EXIT TERM
    printf "%ds to call %s via %s and path <%s>\n" $((t1-t0)) $id $base "$repeaters" |
        tob log.store
    }

main

tob $self.unlock-route

exit

NAME
    call -- initiate a connection to this radio site

EXIT VALUES
    0 -- success
    1 -- some failure occurred
    2 -- failed, no route to site
    3 -- site radio is not powered

DESCRIPTION
    Invoke lock-route to secure a route, then invoke the call method on the
    selected base radio.


