#!/bin/sh

usage="RadioSite.init [--radio CODE] [--id STRING] [--name STRING]"

# create container for radio links to other sites:
tob-new --hide-attr linkto Object

while test -n "$1"; do
    arg=$1 && shift

    case $arg in
        --radio)    
            radio=$1 && shift
            ;;

        --name)    
            name=$1 && shift
            ;;

        --id)    
            id=$1 && shift
            ;;

        *)
            echo RadioSite.init -- unknown argument: $arg >&2
            exit 1
            ;;
    esac

done

test -n "$radio" && 
    echo $radio > \@radio

test -n "$id" && 
    echo $id > \@id

test -n "$name" && 
    echo $name > \@name

tob-new log TimeSeries
tob-new sessions TimeSeries

# this could be done more directly if Cron could be a mixin...
tob-new --hide radio-power Cron
ln -s .radio-power/state-ON radio-power

echo initialized object as $(readlink ^) |
    tob log.store
