#!/bin/sh

usage="RadioSite.init [--radio CODE] [--name STRING]"

# create container for radio links to other sites:
tob-new --hide-attr linkto Object

while test -n "$1"; do
    arg=$1 && shift

    if test $arg == --radio; then
        radio=$1 && shift

    elif test $arg == --name; then
        name="$1" && shift
    else
        echo RadioSite.init -- unknown argument: $arg >&2
        exit 1
    fi
done

test -n "$radio" && 
    echo $radio > \@radio

test -n "$name" && 
    echo $name > \@name

tob-new log TimeSeries
tob-new sessions TimeSeries

echo initialized object as $(readlink ^) |
    tob log.store
