#!/bin/bash

useage="link-add PATH_TO_SITE [INIT ARGS]"

link=$1 && shift

test -e $link/ || {
    # link not found
    test -e $TOB_caller_path/$link/ && 
        link=$TOB_caller_path/$link/
    test -e $link/ || {
        # still not found
        exit 3
        }
    }

link=$(readlink -f $link) ||
    exit 4

name=${link##*/}

tob-new --hide-attr linkto/$name CommServer/RadioLink "$@" &&
    ln -s $link linkto/$name/!


exit

NAME
    link-add -- add a radio link object to a radio site

SYNOPSIS
    link-add PATH_TO_SITE [INIT ARGS]

DESCRIPTION
    Create a new CommServer/RadioLink object in the object.  The init method is
    called after the link object is created, and can take two optional arguments:
    
        --distance DISTANCE
        --visibility NUMBER

    where DISTANCE is in kilometers, and NUMBER is any number from 0 to 1.


