#!/bin/bash

test -d linkto || {
    echo "no linkto/ container found in $TOB_object" 1>&2
    exit 1
    }

test -n "$1" || {
    exec ls linkto
    }

command=$1
case $command in
    add)
        ;;
    del | delete)
        ;;
    show)
        ;;
    *
        command=show
        ;;
esac

# for link in $*; do
#     ls -l linkto/$link
# done


exit

NAME
    link

SYNOPSIS
    RadioSite.link      -- show links
    RadioSite.link foo  -- show link information
    RadioSite.link --add $symlink name  -- add new link 

DESCRIPTION
    


