#!/bin/bash

error () {
    echo "synopsis: radio-hold [set|is on|off]" >&2
    exit 1
    }

test "$1" || {
    test -e radio-hold=ON && echo on && exit
    echo off
    exit
    }

test "$2" || error

shopt -s nocasematch   # allow any case for arg 2, 'on' or 'off'

test $1 = is && { # test assertion and exit with true or false
    state=off
    test -e radio-hold=ON && state=on
    case $2 in
        on)     test $state = on; exit ;;
        off)    test $state = off; exit ;;
        *)      error;;
    esac

    }

test $1 = set || error

# set the attribute to the state given in arg 2:

case $2 in
    on)     touch radio-hold=ON ;;
    off)    test -e radio-hold=ON && rm radio-hold=ON ;;
    *)      error
esac

exit
    
NAME
    radio-hold -- show state, set state, or test assertion of state

SYNOPSIS
    radio-hold [set|is [on|off]]

DESCRIPTION
    Attribute file radio-hold=ON represents state, only exists if state is on.
    
AUTHOR
    ken.irving@alaska.edu (c) 2010

