#!/bin/bash

synopsis="radio-power [set [1|0|on|off]]"

error () {
    printf "%s\n" "$*"
    exit 1
    }

test -n "$1" && {
    test $1 == set || error $synopsis
    new_state=ON
    test -n "$2" && new_state=$2
    case $new_state in
        1|on|On|ON)
            touch radio-power=ON
            ;;
        0|off|Off|OFF)
            test -e radio-power=ON && rm radio-power=ON
            ;;
        *)
            error unknown command: set $new_state
    esac
    }

if test -e radio-power=ON; then
    echo on
else
    echo off
fi
exit
    
NAME
    radio-power -- optionally set or clear radio-power attribute, show state

SYNOPSIS
    radio-power [set [1|on|0|off]]

DESCRIPTION
    print on or off to stdout
    
AUTHOR
    ken.irving@alaska.edu (c) 2010

