#!/bin/bash

synopsis="radio-power [set [1|0|on|off]]"

error () {
    printf "%s\n" "$*"
    exit 1
    }

test -n "$1" && {
    test $1 == set || error $synopsis
    new_state=ON
    test -n "$2" && new_state=$2
    case $new_state in
        1|on|On|ON)
            touch radio-power=ON
            ;;
        0|off|Off|OFF)
            test -e radio-power=ON && rm radio-power=ON
            ;;
        *)
            error unknown command: set $new_state
    esac
    }

test -e radio-power=ON
exit
    
NAME
    radio-power -- optionally set or clear radio-power attribute, return state

SYNOPSIS
    radio-power [set [1|on|0|off]]

DESCRIPTION
    
EXIT STATUS
    0 or 1 (true or false) if radio-power=ON attribute is set or not

AUTHOR
    ken.irving@alaska.edu (c) 2010

