#!/bin/bash

test -e @routes || exit 1

test -n "$1" && limit=$1

here=$(<@id)

n=0
while read -a route; do 
    for link in "${route[@]}"; do
        test -e $link/@id && link=$(<$link/@id)
        printf "%-20s " ${link##*/}
    done
    printf "%-20s\n" $here
    n=$(($n+1))
    test -n "$limit" && test $n -ge $limit && break
done < @routes
