#!/bin/bash

usage="unlock-route [-h] [--help]"

tob=/usr/local/bin/tob

unset tag
test -n "$1" && {
    test $1 == --help && exec awk '/^NAME/{ok=1}ok{print}' $0  
    test $1 == -h && {
        printf "usage: %s\n" "$usage"
        exit 0
        }
    tag=$1
    test $tag == $(<@id) ||
        printf "tag %s does not match node id %s\n" $tag "$(<@id)"
    }

test -e @LOCK || exit 3  # lock file does not exist
test -s @LOCK || exit 2  # lock file is empty
nodes=($(<@LOCK) .)
locks=(${nodes[@]/%/\/@LOCK})
rm -f ${locks[@]} || {
    printf "failed to remove lock(s) for %s\n" "$(<@id)" >&2
    for node in "${nodes[@]}"; do
        test -e $node/@LOCK && 
            printf "\t%s lock remains\n" "$(<$node/@id)" >&2
    done
    exit 1
    }

exit

NAME
    unlock-route

EXIT VALUES
    0 -- success, locks were removed
    1 -- failed to remove one or more locks
    2 -- lock is owned by another node, no change
    3 -- object was not locked

DESCRIPTION
    The file @LOCK contains the route to reach the object node,
    while the @LOCK files in the route nodes are empty.

AUTHOR
    ken.irving@alaska.edu 2010

