#!/bin/bash

usage="unlock-route [-h] [--help] [TAG]"

tob=/usr/local/bin/tob

test -n "$VERBOSE" && {
    printf "\t%s (%s): VERBOSE is set\n" ${TOB_object##*/} $(<@id) >> /tmp/verbosity.txt
    }

unlock-route () {
    for node in $(<@LOCK); do
        test -n "$tag" && {
            test "$(<$node/@LOCK)" == $tag || {
                contents=$(<$node/@LOCK)
                printf "%s lock contains '%s', not '%s'\n" $node $contents $tag >&2
                return 1
                }
            }
        rm $node/@LOCK || {
            nolock="$nolock ${node##*/}"
            m=$(($m + 1))
            continue
            }
        n=$(($n + 1))
        nodes="$nodes ${node##*/}"
        test -n "$VERBOSE" &&
            printf "\t(tag %s) unlocked %s\n" $tag ${node##*/}
    done
    return 0
    }

main () {
    test -e @LOCK || exit 3
    test -s @LOCK || exit 2
    nodes=""
    nolock=""
    n=0
    m=0
    unset nplural
    unset mplural
    unlock-route && rm @LOCK && n=$(($n + 1)) || {
        test $n -gt 1 && nplural=s
        echo failed to remove lock$nplural in $node$nplural | $tob log.store
        return 1
        }
    test $n -gt 1 && nplural=s
    msg="removed $n lock$nplural: $nodes ${TOB_object##*[./]}"
    test -n "$nolock" && {
        test $m -gt 1 && mplural=s
        msg="$msg, missing $m lock$mplural:$nolock"
        }
    test -n "$NOLOG" ||
        echo $msg | $tob log.store
    }

while test -n "$1"; do
    tag=$1 && shift
    if test $tag == --no-log; then
        unset tag
        NOLOG=1
    elif test $tag == -h; then
        echo "$usage"
        exit 0
    elif test $tag == --help; then
        exec awk '/^NAME/{ok=1}ok{print}' $0  
    fi
done

main

exit

NAME
    unlock-route

EXIT VALUES
    0 -- success, locks were removed
    1 -- failed to remove one or more locks
    2 -- lock is owned by another node, no change
    3 -- object was not locked

DESCRIPTION
    The file @LOCK contains the route to reach the object node,
    while the @LOCK files in the route nodes are empty.

AUTHOR
    ken.irving@alaska.edu 2010

