#!/bin/sh

hops=( $@ ) 

test -n "$hops" ||
    hops=( $TOB_object )

# echo HOPS: ${hops[*]}

test -e @ip2radio && {
    # done: reached base radio
    IFS=: 
    echo "${hops[*]}"
    exit 0
    }

test ${#hops[@]} -lt 5 || {
  # echo too many hops: ${hops[@]} >&2
    exit 0
    }

name=$TOB_object

# echo in $name ${hops[@]}

for up in _/*; do

  # echo TESTING $up

    test -L $up || {
        echo bad uplink: $up >&2
        exit 1
        }

    test -d $up/ || {
        echo link is not a directory: $up >&2
        exit 1
        }

    # skip if 'up' is already in hops list:
    # (a hash test might be preferable)
    for hop in ${hops[@]}; do
      # echo test $hop == $up ...
        test $hop == $up &&
            continue 2
    done

  # echo tob $up.up ${hops[@]} $up

    tob $up.up ${hops[@]} $up ||
        exit 1

  # path=$(tob $up.up ${hops[@]} $up)
  # test $? -eq 1 && exit 1
  # echo PATH: $path
  # test $? -eq 2 && continue

done
    
