#!/bin/sh

hops=( $@ ) 

test -n "$hops" ||
    hops=( $TOB_object )

test -e @ip2radio && {
    IFS=: 
    echo "${hops[*]}"
    exit 0
    }

test ${#hops[@]} -lt 5 ||
    exit 0

for up in _/*; do

    test -L $up ||
        exit 1

    test -d $up/ ||
        exit 1

    # skip if 'up' already visited:
    for hop in ${hops[@]}; do
        test $hop == $up &&
            continue 2
    done

    tob $up.up ${hops[@]} $up ||
        exit 1

done
    
