#!/bin/sh

test -n "$1" || 
    exec $0 $(readlink -f $PWD) > @uplinks

test -e @ip2radio && {
    IFS=: 
    echo "$*"
    exit 0
    }

test $# -lt 5 ||
    exit 0

for up in _/*; do

    test -L $up -o -d $up ||
        exit 1

    up=$(readlink -f $up)

    for hop in $*; do
        test $hop == $up &&
            continue 2
    done

    tob $up.up $* $up ||
        exit 1

done
    
