#!/bin/sh

test -n "$1" || {
    tm=$(date +%s)
    $0 $(readlink -f $PWD) > @routes
    tm=$(($(date +%s) - $tm))
    echo update routes n=$(wc -l < @routes) tm=$tm |
        tob log.store
    tob ..rank-routes
    exit 
    }

test -e %ip2radio && {
    # drop the first node, output the rest in reverse order:
    shift 
    result=$1
    shift
    while test -n "$1"; do
        result="$1 $result"
        shift
    done
    echo $result
    exit 0
    }

test $# -le 5 ||
    exit 0

for up in _/*; do

    test -L $up -o -d $up ||
        exit 1

    up=$(readlink -f $up)

    for hop in $*; do
        test $hop == $up &&
            continue 2
    done

    # invoke this method by name using thinobject dispatcher:
    tob $up.${0##*/} $* $up ||
        exit 1

done
    
