#!/bin/sh

usage="RadioBase.init [--radio CODE] [--name STRING] [--host IP] [--port NUM]"

while test -n "$1"; do
    arg="$1" && shift

    if test $arg == --radio; then
        radio=$1 && shift

    elif test $arg == --name; then
        name="$1" && shift

    elif test "$arg" == --host; then
        host="$1" && shift

    elif test "$arg" == --port; then
        port="$1" && shift

    else
        echo RadioBase.init -- unknown argument: $arg >&2
        exit 1
    fi

done

test -n "$host" && 
    echo host = $host > \%ip2radio

test -n "$port" && 
    echo port = $port >> \%ip2radio

## there some annoying problem with super... so avoid calling super.init:
## # continue to the init method in the RadioSite super class:
## tob ..super.init $args

## the following should be done in super-class method init:

# create container for radio links to other sites:
tob-new --hide-attr linkto Object

test -n "$radio" && 
    echo $radio > \@radio

test -n "$name" && 
    echo $name > \@name

tob-new log TimeSeries

echo initialized object as $(readlink ^) |
    tob log.store
