#!/bin/sh

name=${TOB_object##*/}

tag=$(<@tag)

pid=$(<.@pid)

test "${pid#* }" == "$pid" && {
    # pid value does not contain a space, so should be a valid or stale pid
    test -d /proc/$pid || {
        # pid is stale, so add the timestamp to the pid attribute:
        time=$(date --iso=seconds)
        pid="($time $pid)"
        echo "$pid" > .@pid
        }
    }

lock='_'
test -e @LOCK && lock=L

state=$(<@state)

printf "%10s %s %20s %s %s\n" $name $lock $tag "$pid" $state
