#!/bin/sh

name=${TOB_object##*/}

tag=$(<@tag)

pid=$(<.@pid)
test -d /proc/$pid || pid="($pid)"

lock='_'
test -e @LOCK && lock=L

state=$(<@state)

printf "%10s %s %20s %s %s\n" $name $lock $tag $pid $state
