#!/bin/bash

log=/tmp/commserver-cleared-locks

tob=/usr/local/bin/tob
self=.

maxage=3600
test -n "$1" && maxage=$1

time=$(/bin/date --iso=sec)
while read record; do
    test "${record#*--}" == "$record" && continue # line does not show a lock
    age=${record%% *}

    test $age -gt $maxage || continue

    target=${record% --*}
    target=${target##* }

    $tob $target.unlock-route

    if test $? == 0; then result="OK"; else result="FAILED"; fi

    printf "%s, %s.unlock-route, %s, %s\n" $time $target $result "$record" >> $log
    
done < <($tob $self.show-locks --age)

exit

NAME
    CommServer.clear-stale-locks

DESCRIPTION
    Intended to be run periodically from cron, the cleared-stale-locks method 
    inspects the output from the CommServer.show-locks --age method to find
    locks that have been in place longer than the specified or default maximum
    age.

    Output of show-locks --age looks like:

        $ commserver.show-locks --age
        38 toolik --> imnavait-mtn --> itik-rep --> hatboxmesa -- 17436
        99 deadhorse --> fb-rep --> white-hills --> may-ck -- 17626

    A record should be written to the log file if a 'stale' lock is found and
    removed.

AUTHOR
    Ken.Irving@alaska.edu 2010

