#!/usr/bin/perl
# !/usr/bin/perl -w
use strict;
use warnings;

$| = 1;

use constant PROMPT => 'query: ';
print PROMPT;

while ( <> ) { # read input from the client
    chomp;
    s/\r//;

    if ( m/^\s*$/ ) { } # skip blank lines 

    elsif ( m/^\s*#/ ) { } # skip comment lines

    elsif ( m/^h(elp)?$/i ) { # action command
        help_screen();
        }

    elsif ( m/^q(uit)?$/i ) { # action command
        print "goodbye!\n";
        exit 0;
        }

    elsif ( m/^call\s+(.+)$/ ) { # load and call with query parameters
        my $site = $1;
        $site =~ s/\r//;
        die "unable to resolve $site\n" unless -d $site;
        exec "/usr/local/bin/tob $site.call";
        }

    else {
        print "unknown query: $_, try:\n";
        help_screen();
        }
    print PROMPT;
    }

exit 0;

sub help_screen {
    print << "    END_HELP";
    help -- display this message
    quit -- close down session
    call -- call specified site
    END_HELP
    }

