#!/bin/bash

error() { echo "$@" >&2 && exit 1; }

queue=.q
spool=.q-spool
test -d $spool && test -d $queue || error CommSite object not initialized

while -n "$1"; do
    arg=$1 && shift
    case $arg in

        h)      echo SYNOPSIS: commserver.pick-site-to-call [-h|--help]
                ;;

        help)   awk '/^NAME$/{ok=1}ok{print}' $0
                ;;

        *)      error unknown argument: $arg
                ;;
    esac
done

touch .NOW

# process spool for queue, moving sites into queue unless delay 
for site in .q-spool/*; do
    # leave site in spool if also in queue:
    test -e $q/${site#*/} && continue

    # move site into queue if no delay attribute:
    test -e $site/q-DELAY || mv $site $q && continue

    # move site into queue if delay has expired:
    test $site/q-DELAY -nt .NOW || mv $site $q && continue
done

# process queue...

for site in .q/*; do

    # remove site from queue if timeout has elapsed:
    test $site/q-TIMEOUT -nt .NOW || rm $site && continue

done
exit 0

NAME
    CommServer.pick-site-to-call -- process call queue spool and queue

DESCRIPTION
    The goal is to select a site to call after weighing various metrics,
    including time since last contact, caller-assigned priority, availability
    cost of routes, and perhaps others.

    The CommServer.call method provides the caller interface to this method,
    creating an object in the queue spool.  This method moves objects from
    the spool into the queue, unless the optional delay interval has not 
    elapsed.

    Each object in the queue is evaluated along with the others, and one
    chosen...

    Objects are removed from the queue if the timeout period has elapsed.

IMPLEMENTATION NOTES
    The queue is a form of priority queue, where the effective priority
    metric is not fully defined on entry to the queue, but also depends
    dynamically with availability and cost of routing nodes and on other
    factors.

OPTIONS
    
AUTHOR
    Ken.Irving@alaska.edu 2010


