#!/bin/bash
# CommServer.run -- run the server, reading from .q-spool into .q until empty

# exit if an instance is already running (pid file exists and is not stale):
# test -s .@PID && exit 1
test -s .@PID && test -d /proc/$(<.@PID) && exit 1
trap 'rm .@PID' TERM EXIT
echo $$ > .@PID

# close stdin, redirect stdout and stderr to files:
exec 0>&- 1>.@OUT 2>.@ERR

warn() { echo "$@" >&2; }
error() { warn "$@" && exit 1; }

tob=/usr/local/bin/tob

queue=.q
spool=.q-spool

# read settings from config file:
test -e : -o -e .: && {
    rcfile=.: && test -e : && rcfile=: # rc file : supersedes .:
    unset ok
    while read -r tag value; do
        test "${tag:0:1}" == '[' && {
            block=$tag
            continue
            }
        test "$block" == '[run]' || continue
        value=${value#*=}
        value=${value## }
        case $tag in
            sleep_sec) sleep_sec=${sleep_sec:-$value};;
            random_mod) random_mod=${random_mod:-$value};;
            random_ofs) random_ofs=${random_ofs:-$value};;
            '') true;; # ignore blank line
            *) warn "unknown attribute in $rcfile: {$tag}";;
        esac
    done < "$rcfile"
    }

test -n "$sleep_sec" || sleep_sec=2

# set maximum radio hops (4 repeaters max):
max_hops=5

process_spool() { # move sites into queue unless delay, return 0 if empty
    delayed=0
    despooled=0
    for site in .q-spool/*; do
    
        id="${site##*/}"
        test "$id" == '*' && return 0
    
      # echo spooled: $id
    
        # leave site in spool if also in queue:
        # ... NO ... drop it from the spool if that's the case
        test -e $queue/$id && {
            rm $site
            echo drop duplicate $site from spool
            continue
            }
    
        # move site into queue if no delay attribute:
        test -e $site/q-DELAY || {
            mv $site $queue
            queued=$(($queued+1))
            despooled=$(($despooled+1))
            continue
            }
    
        # move site into queue if delay has expired:
        test $site/q-DELAY -nt .@NOW || {
            mv $site $queue
            queued=$(($queued+1))
            despooled=$(($despooled+1))
            continue
            }
    done
    test $despooled -gt 0 && return 2
    return 1
    }

declare -A available

check_node() { # see if node is available for connections, encode in a hash
    local node=$1
    test ${node:0:1} != / && {
        # node is relative, so also check the absolute or canonical form:
        local canonical=$(readlink -f $node)
        test -n "${available[$canonical]}" || check_node $canonical # recurse!
        available[$node]=${available[$canonical]}
        test "${available[$node]}" == y && return 0
        return 1
        }
    # node is absolute, so check the node attributes and store y or n:
    test -e $node/radio-power=ON -a ! -e $node/@LOCK && available[$node]=y && return 0
    available[$node]=n && return 1
    }

choose_route() { # given a site, find first available route
    site=$1
    test -e $site/@routes || return 2 ## return value 2 means: no routes defined for site
    case ${available[$site]} in
        y)  true;;
        n)  false;;
        '') check_node $site;;
    esac || return 1
    ## assert: the site is powered and not locked, so iterate on its @routes list
    local max_hops=$max_hops
    test -e $site/@max-hops && max_hops=$(<$site/@max-hops) ## bad! should check tob attribute...
    ## 
    unset route
    while read -a rte; do
        test ${#rte[@]} -gt $max_hops && continue # too many hops, try next route ...
        for node in ${rte[@]}; do
            case ${available[$node]} in
                y)  true;;
                n)  false;;
                '') check_node $node
            esac || continue 2
        done
        ## assert: all nodes in this route are available
        route=(${rte[@]}) # chosen route is in global array variable route
        return 0
    done < $site/@routes
    return 1
    }

process_queue() { # return value: 0 if empty, else 1
    unset choice maxweight
    n=0
    weights=()
    for site in $queue/*; do
    
        id="${site#*/}"
        test "$id" == '*' && return 0 
    
        # remove site from queue if timeout has elapsed:
        test $site/q-TIMEOUT -nt .@NOW || {
            touch $site/q-FAILED
            rm $site
          # echo timeout: $site
            tmouts=$(($tmouts+1))
            continue
            }
    
        # work around bug that .q/site.foo has to be .q.site.foo:
        tsite=${site/\//.}

        # aquire a route or skip this site:
        test -n "${available[$site]}" || check_node $site
        test "${available[$site]}" == y || continue
        choose_route $site || continue

        test -n "$route" || continue

        # calculate one or more metrics based on the route...
    
        # metric for number of hops over minimum:
        min_hops=1
        test -e $site/@min-hops && min_hops=$(<$site/@min-hops)
        extra_hops=$(( (${#route[@]} - $min_hops) * 20 ))
    
        # age is time in seconds since last successful session:
        age=0
        test -e $site/@session &&
            age=$((now - $(stat -c %Y $site/@session)))
        # convert age to crude/approximate logarithmic value:
        test $age -lt 0 && age=0
        age=$(( (${#age} - 1)* 10 + ${age:0:1} ))
    
        sum=$(( $age - $extra_hops ))
    
        test -e $site/q-PRIORITY && 
            sum=$(( $sum + $(<$site/q-PRIORITY) ))
    
        test -e $site/q-PRIORITY=* && {
            value=$(ls $site/q-PRIORITY=*)
            sum=$(( $sum + ${value#*=} ))
            }
    
        test -n "$random_mod" &&
            sum=$(( $sum + $RANDOM % $random_mod + $random_ofs ))
    
        test -n "$maxweight" || maxweight=$((sum-1))

        n=$((n+1))
        weights=(${weights[@]} $sum)
        test $sum -gt $maxweight || continue
        maxweight=$sum
        choice=$site

    done
    return 1
    }

check_notify_pool() { # check candidates for timeout
    for site in .q-notified/*; do
    
        id=${site##*/}
        test "$id" == '*' && return 0
    
      # echo notified: $site
    
        # move site into queue if delay has expired:
        test $site/q-TIMEOUT -nt .@NOW && continue

        # timeout has expired, so unlock route and remove site from pool
        s=$(readlink -f $site)
        rm $site
        notified_tmouts=$(($notified_tmouts+1))
        $tob $s.unlock-route $id
        
      # echo timeout: $site removed from notified, unlocked

        ## NOTE: the above may have/be a race condition, so needs work...
        ## we remove the link before unlocking the route... maybe that's ok?
    
    done
    return 1
    }

check_locks() { # release lock if the pid value it contains is not active
    for lockpid in .q-lock/*; do
        test "${lockpid: -1:1}" == '*' && return 0 
        test -e /proc/$(<$lockpid) && continue
        site=${lockpid##*/}
        test -e $site/@LOCK || { # already unlocked
            rm $lockpid
            continue
            }
        $tob $site.unlock-route
        printf "stale: %s.unlock-route returned %s\n" $site $?
        rm $lockpid
        stale=$((stale+1))
    done
    }

check_base_nodes() { # return false unless at least one base is available
    test -d .bases || return 2
    for base in .bases/*; do
        test -e $base/radio-power=ON -a ! -e $base/@LOCK && return 0
    done
    return 1
    }

date +%s > .@START

loops=0
passed=0
queued=0
tmouts=0
notified_tmouts=0
stale=0
while true; do
    # quit if the pid file is not set
    test -s .@PID || error pid file .@PID was removed or reset

    date +%s > .@NOW
    now=$(<.@NOW)

  # process_spool && process_queue && check_notify_pool && exit 0

    process_spool; scan_spool=$?
    check_locks
    # process_queue() will make a choice if possible:
    process_queue; scan_queue=$?
    check_notify_pool; scan_notified=$?
    
    available=()

    # exit values from the above will be 0 when directory is empty, i.e. done
    test $scan_spool == 0 -a $scan_queue == 0 -a $scan_notified == 0 && {
        elapsed=$(($(date +%s)-$(<.@START)))
        printf "%s.%s exiting after %d/%d passed/queued, %d+%d timeouts, %d loops, %d stale, %ds\n" \
            $TOB_object $TOB_method $passed $queued $tmouts $notified_tmouts $loops $stale $elapsed
        printf "%d passed, %d queued, %d q-tmout, %d n-tmout, %d loops, %d stale, %ds\n" \
            $passed $queued $tmouts $notified_tmouts $loops $stale $elapsed | \
            $tob $self.log.store
        exit 0
        }

    loops=$(($loops + 1))

    test -n "$choice" || {
        sleep $sleep_sec
        continue
        }
    
    printf "SELECT (%d) %s from %d choices, %ds (%s)\n" \
        $maxweight ${choice##*/} $n $(($(date +%s)-now)) "${weights[*]}"

    test -e $choice || error ERROR: $choice not found

    tsite=${choice/\//.}
    
    id=$(<$choice/@id)
    $tob $tsite.lock-route $id || {
        # should have worked, so just bail and better luck next time
        echo failed to aquire route to $choice... >&2
        sleep $sleep_sec
        continue
        } 

    # ASSERT: the route to $choice is locked, ready to go!
    # should we check that this route is the same as the one checked above? Nah.
    
    touch $choice/q-PASSED
    
    # remove site from queue:
    rm $choice || error failed to dequeue $choice...
  # echo dequeued: $choice
    passed=$(($passed+1))

    sleep $sleep_sec
done

exit

NAME
    CommServer.run -- process call queue spool and queue

DESCRIPTION
    The goal is to select a site to call after weighing various metrics,
    including time since last contact, caller-assigned priority, availability
    cost of routes, and perhaps others.

    The CommServer.call method provides the caller interface to this method,
    creating an object in the queue spool.  This method moves objects from
    the spool into the queue, unless the optional delay interval has not 
    elapsed.

    Each object in the queue is evaluated along with the others, and one
    chosen...

    Objects are removed from the queue if the timeout period has elapsed.

IMPLEMENTATION NOTES
    The queue is a form of priority queue, where the effective priority
    metric is not fully defined on entry to the queue, but also depends
    dynamically with availability and cost of routing nodes and on other
    factors.

    The age in seconds is converted to something like a logarithm in base
    10 by concatenating the number of digits minus 1 and the first digit.

OPTIONS
    
AUTHOR
    Ken.Irving@alaska.edu 2010


