#!/bin/bash

tob=/usr/local/bin/tob

error() { echo "$@" >&2 && exit 1; }

printf "sites spooled: %d, queued: %d\n" $(ls .q-spool|wc -l) $(ls .q|wc -l)

test "$1" == '--monitor' -o "$1" == '-m' || exit 0

tail -F .@{PID,OUT,ERR}
    



exit

NAME
    CommServer.status -- show status of commserver queue, spool, etc.

DESCRIPTION

OPTIONS
    
AUTHOR
    Ken.Irving@alaska.edu 2010


