#!/bin/sh

synopsis='logger-var [-h] [--priority N] [TABLE.]VARNAME[.INDEX] [ OP VALUE ]

error () {
    echo "$*" 2>&1
    exit 1
    }

# parse options:
while test "${1:0:1}" == '-'; do
    opt=$1
    shift
    case $opt in
        --priority*)     echo "$synopsis"
                priority=$1
                shift
                ;;
        -h)     echo "$synopsis"
                exit 0
                ;;
        *)      echo unknown option: $opt 2>&1
                exit 1
                ;;
    esac
done

var=$1
test -n "$var" || {
    echo "$synopsis" 2>&1
    exit 1
    }

parse_table_variable_index () {
    var=$1
    table=public
    unset index
    }

parse_table_variable_index $var

cmd=( get-variable $site.$table.$var )


    set-variable cr9000 public multi_dim {2 1 3} 3.14159


test -n "$2" || { # get variable value


    }

op=$2
value=$3

test -n "$value" || error "$synopsis"


